<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Clayton" ignored="0" name="Default test" tests="12" failures="2" timestamp="21 Feb 2018 14:46:53 GMT" time="62.179" errors="0">
  <testcase name="NavigateToBatchListTab" time="3.431" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="FindAllBatchesTag" time="1.066" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="BatchNameTest" time="43.849" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="InputFromDateFields" time="0.756" classname="com.revature.test.admin.testclasses.BatchListTest">
    <failure type="java.lang.AssertionError" message="Error: Could not input a valid date into &amp;apos;from&amp;apos; date field">
      <![CDATA[java.lang.AssertionError: Error: Could not input a valid date into 'from' date fieldat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.BatchListTest.InputFromDateFields(BatchListTest.java:69)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- InputFromDateFields -->
  <testcase name="InputToDateFields" time="0.521" classname="com.revature.test.admin.testclasses.BatchListTest">
    <failure type="java.lang.AssertionError" message="Error: Could not input a valid date into &amp;apos;to&amp;apos; date field">
      <![CDATA[java.lang.AssertionError: Error: Could not input a valid date into 'to' date fieldat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.BatchListTest.InputToDateFields(BatchListTest.java:79)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- InputToDateFields -->
  <testcase name="ClickFromField" time="0.723" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="ClickToField" time="1.437" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="ClickSubmit" time="0.166" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="areResultsCorrect" time="1.277" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="ClickReset" time="0.174" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="allBatchesShowing" time="2.259" classname="com.revature.test.admin.testclasses.BatchListTest"/>
  <testcase name="useCase1" time="6.403" classname="com.revature.test.admin.testclasses.BatchListTest"/>
</testsuite> <!-- Default test -->
